-- COLLECTION SYSTEM DATABASE SCHEMA
-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- 1. COLLECTION SCHEDULES TABLE
CREATE TABLE IF NOT EXISTS collection_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id BIGINT REFERENCES centers(id) ON DELETE CASCADE,
    center_name TEXT, -- Denormalized for quick frontend display
    scheduled_date DATE NOT NULL,
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Approved', 'Completed'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    approved_at TIMESTAMPTZ,
    approved_by TEXT -- Manager's Staff ID
);

-- DISABLE RLS for this new table (Development ease)
ALTER TABLE collection_schedules DISABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE collection_schedules TO anon, authenticated, postgres, service_role;

-- 2. DUMMY DATA FOR TESTING (Optional)
-- INSERT INTO collection_schedules (center_id, center_name, scheduled_date, status)
-- VALUES (1, 'Test Center', CURRENT_DATE, 'Pending');
