-- 1. ADD DISBURSEMENT COLUMNS TO LOANS
ALTER TABLE loans 
ADD COLUMN IF NOT EXISTS disbursement_status TEXT DEFAULT 'PENDING', -- 'PENDING', 'CREDITED'
ADD COLUMN IF NOT EXISTS credited_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS amount_sanctioned NUMERIC;

-- 2. ENSURE PD_VERIFICATIONS HAS STATUS FOR STATS
ALTER TABLE pd_verifications 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending';

-- 3. UPDATE MANAGER CONTROL SCHEDULES TO TRACK DISBURSEMENT REF
ALTER TABLE collection_schedules 
ADD COLUMN IF NOT EXISTS loan_id BIGINT;
