const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const URL = process.env.SUPABASE_URL;
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(URL, KEY);

async function setup() {
    console.log('Creating collection_schedules table...');
    
    const sql = `
    CREATE TABLE IF NOT EXISTS collection_schedules (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        center_id BIGINT REFERENCES centers(id) ON DELETE CASCADE,
        center_name TEXT,
        scheduled_date DATE NOT NULL,
        status TEXT DEFAULT 'Pending',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        approved_at TIMESTAMPTZ,
        approved_by TEXT
    );
    ALTER TABLE collection_schedules DISABLE ROW LEVEL SECURITY;
    GRANT ALL ON TABLE collection_schedules TO anon, authenticated, postgres, service_role;
    `;

    // Note: Supabase JS client doesn't support arbitrary SQL execution easily 
    // unless a custom RPC is set up. We'll try to insert a dummy record instead
    // to check if table exists, or just provide the SQL for the user.
    
    console.log('--- PLEASE RUN THE FOLLOWING SQL IN YOUR SUPABASE SQL EDITOR ---');
    console.log(sql);
    console.log('---------------------------------------------------------------');
    
    process.exit(0);
}

setup();
